### ISSUE TITLE
Login required

### ISSUE THREAD

**Issue by Der-K-2000** [nikos90/instagram_upload#1]
Correct login, but it says:

```
stdClass Object
(
    [status] => fail
    [message] => login_required
)
```

**Comment by nikos90** [comment]
check the cookies.txt file. 
Does it contain the login credentials? If not make the file writable and let me know.

**Comment by Der-K-2000** [comment]
Awesome. That was it. Thank you! Why the heck all of the thousands uploading scripts doesn't work, but your "simple" one?

**Comment by nikos90** [comment]
Mine is pretty new ;)
Enjoy!

**Comment by Levapishe** [comment]
HI! Good job! I've uploaded in XAMPP and run it on my PC => script added chosen photo => than i've taken another one and error
