### ISSUE TITLE
Upload 

### ISSUE THREAD

**Issue by Levapishe** [nikos90/instagram_upload#2]
HI! Good job! I've uploaded in XAMPP and run it on my PC => script added chosen photo to instagram profile  => than i've taken another one and error occured:

stdClass Object
(
[status] => fail
[lock] => 
[message] => checkpoint_required
[checkpoint_url] => https://i.instagram.com/integrity/checkpoint/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss
)

What i must do/change?

**Comment by nikos90** [comment]
Login to your account on your browser.
You will have to validate your account. After that you will be fine.

**Comment by Levapishe** [comment]
Thank you! Phone validation. Can this validation occur due to different user-agents? Maybe you know how to bypass this?

**Comment by nikos90** [comment]
It's possible to occur due to different user-agents.
I can't tell for sure. But if this is the case then, there is not a possible workaround.
If you rotate user agents, you have to redo this step for each one.
If you keep using the current user agent, it won't show up again.

You are welcome! Enjoy!

**Comment by Levapishe** [comment]
Hmmm i tried sms-service and validate - 1 minute and ban) Instagram knows all sms-services maybe) Today i'll try your script with my user-agent.

**Comment by nikos90** [comment]
Ok.
Update me if you can with the result.
Thanks

**Comment by Levapishe** [comment]
Testing this = 1 photo uploading good and than validation. User-agents don't help.

**Comment by nikos90** [comment]
hmmm interesting..
So it's not related to user-agents.
